config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/logout' => 'sessions#destroy'

  #delete '/logout' => 'sessions#destroy'
  #not sure why 'delete' method/request doesnt work, but 'get' does?
  #get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/auth/:provider/callback' => 'sessions#create' 
  #dynamic route that i'll use when adding github omniauth
#if I end up hosting this to heroku, ill need to go to :
# https://console.cloud.google.com/apis/credentials/oauthclient/322165384303-1k9tckicc9918m1kgqeit1bdg9vln021.apps.googleusercontent.com?project=rails-project-302302&supportedpurview=project
# and add another authorized uri
  resources :reactions
  resources :dreams do
    resources :reactions, only: [:new, :index]
  end
  resources :themes
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  belongs_to :theme
  has_many :reactions 
  has_many :users, through: :reactions

  validates :title, presence: true
  validates :content, presence: true

  accepts_nested_attributes_for :theme, reject_if: proc { |attributes| attributes['name'].blank? }

  def self.search(params)
    where("LOWER(title) LIKE :term OR LOWER(content) LIKE :term", term: "%#{params}%")
  end
  #why do we add 'params' in SQL Query?
  #It prevents someone from injecting code that will delete entire database.. we are specifically asking to see if a title euqalis that name
  #instead of sneaking in a closing quote that impacts the sql queary that can delete db

  #line 13 - use symbol term instead of '?' to keep DRY and send hash params

  # def self.alpha 
  #   order(:title)
  # end

  # def theme_attributes=(attributes)
  #   # binding.pry
  #   theme = Theme.find_or_create_by(attributes) if !attributes['name'].empty?
  # end
  #can i change this up to serve as a validation? where if the attributes are empty you create it, or if they match by name then you send error message with "theme name already exists"
  #has to be a simpler way... uniqueness validation didnt work but I might've done scope wrong

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_dream, only:[:show, :edit, :update]
  before_action :redirect_if_not_dream_user, only:[:edit, :update]

  def new
    @dream = Dream.new
    @dream.build_theme
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = session[:user_id]
    if @dream.save #validation occurs here
      redirect_to dream_path(@dream)
    else
      @dream.build_theme
      render :new
    end
  end

  def index
    @dreams = Dream.all 
    if params[:q] && !params[:q].empty?
      @dreams = @dreams.search(params[:q].downcase)
    end
  end

  def show 
  end

  def edit 
  end

  def update 
    if @dream.update(dream_params)
      redirect_to dream_path(@dream)
    else
      render :edit 
    end
  end

  private 

  def dream_params 
    params.require(:dream).permit(:title, :content, :theme_id, theme_attributes: [:name, :description])
  end

  def set_dream
    @dream = Dream.find_by_id(params[:id])
    redirect_to dreams_path if !@dream
  end

  def redirect_if_not_dream_user
     redirect_to dreams_path if @dream.user != current_user
  end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/edit.html.erb
<h1>Edit Your Dream</h1>

<%= form_for(@dream) do |f| %>

<div> 
  <%= f.label :title %>
  <%= f.text_field :title %>
</div> 
<div> 
  <%= f.label :content %>
  <%= f.text_area :content %>
</div> 

<%= submit_tag "Edit Dream" %>

<% end %>

app/views/dreams/index.html.erb
<h1>All Dreams</h1>
<%# using a form_tag bc we aren't creating/updating/editing an object, we're searching for the title or attribute of many dreams (only querying data/parameters) and then we compare the search terms. We wanna keep a broader search, as opposed to form_for where we would be stuck with exact attributes of object we're searching. We don't wanna limit ourselves to just the attributes %>
<%= form_tag("/dreams", method: 'get') do %> <%# we use a get request instead of post request bc it sends the parameters into the URL - this is important because when you copy, paste and share URL it saves the search params to go to that exact page %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

<%# if @dreams.empty? %>

<%# <h2>No dreams yet! Post your dream <%= link_to "here", new_dream_path %>

<% @dreams.each do |dream| %>
<h2><%= link_to dream.title, dream_path(dream.id) %></h2>
<h3><em><%= dream.theme.name %></em></h3>
<p><%#= dream.content %></p>
by: <%= dream.user.username %>
<%#= link_to "Write a Reaction", new_dream_reaction_path(dream.id) if dream.user != current_user %>

<% end %>

app/views/dreams/new.html.erb
<h1>Add a New Dream</h1>

<%= render partial: 'layouts/errors', locals: {object: @dream} %>

<%= form_for(@dream) do |f| %>

<div>
<%= f.label :title %>
<%= f.text_field :title %><br><br>
</div>
<div>
<%= f.label :content %>
<%= f.text_area :content %>
</div>

<%#= if dream.save? %>
<%#= yield %>

<p>Select a theme that best describes your dream: </p>

<div>

<%= f.collection_select :theme_id, Theme.all, :id, :name, include_blank: 'Select One' %>
</div>

<p>Or create a new theme: </p>


<%= f.fields_for :theme do |theme_fields| %>
<%# Why wouldnt we use 'f.fields_for @theme.build_dream'?
Because when we create this nested form and the edit functionality, the form will override any previous associations 
between the dream and theme %>
<div>
  <%= theme_fields.label :name %>
  <%= theme_fields.text_field :name %><br><br>
</div>
<div>
  <%= theme_fields.label :description %>
  <%= theme_fields.text_area :description %><br><br>
</div>

<% end %>


<%= f.submit "Add Dream" %>


<% end %>

app/views/dreams/show.html.erb
<h2><%= @dream.title %></h2>
<h3><em><%= @dream.theme.name %></em></h3>
<p><%= @dream.content %></p><br>

by: <%= @dream.user.username %><br>
<%= link_to "Edit #{@dream.title}", edit_dream_path(@dream) if @dream.user == current_user %><br>
<%= link_to "Write a Reaction", new_dream_reaction_path(@dream.id) if @dream.user != current_user %>