config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/logout' => 'sessions#destroy'

  #delete '/logout' => 'sessions#destroy'
  #not sure why 'delete' method/request doesnt work, but 'get' does?
  #get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/auth/:provider/callback' => 'sessions#create' 
  #dynamic route that i'll use when adding github omniauth
#if I end up hosting this to heroku, ill need to go to :
# https://console.cloud.google.com/apis/credentials/oauthclient/322165384303-1k9tckicc9918m1kgqeit1bdg9vln021.apps.googleusercontent.com?project=rails-project-302302&supportedpurview=project
# and add another authorized uri
  resources :reactions
  resources :dreams do
    resources :reactions, only: [:new, :index]
  end
  resources :themes
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reactions
  has_many :dream_reactions, through: :reactions, source: :dream
  has_many :dreams

  validates :username, uniqueness: true, presence: true

  has_secure_password

  #username instead of email bc we want to avoid different people creating same usernames and potentially logging in to other person's acct, so we set the username to be the email...thought this was avoided w/ uniqueness validation????
  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u|
      u.password = SecureRandom.hex
    end
  end

  def self.create_by_github_omniauth(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u|
      u.password = SecureRandom.hex 
    end
  end

end

#moved the create_by_google_omniauth method out of sessionscontroller to model bc in bigger apps or if our user has a lot more properties, it performs better in user model.


#ICS - 25

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show 
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  private

  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for(@user) do |f| %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Sign Up" %>
<%# if we put password_digest instead of password, we would be setting the new user's password to a raw string
it would not be hashed, salted. We'd be overriding the authentication. %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>


<h2>Welcome to <%= @user.username%>'s homepage! </h2>

<h3>Here are the dreams <%=@user.username%> reacted to :</h3>
<ul>
  <% @user.dream_reactions.each do |dr|%>
  <li> <%= link_to dr.title, dream_reactions_path(dr)%> </li>
  <% end %>
</ul>

<%# The UI/UX will be dramatically improved -> will create streamlined welcome page  %>