config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  get '/logout' => 'sessions#destroy'

  #delete '/logout' => 'sessions#destroy'
  #not sure why 'delete' method/request doesnt work, but 'get' does?
  #get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/auth/:provider/callback' => 'sessions#create' 
  #dynamic route that i'll use when adding github omniauth
#if I end up hosting this to heroku, ill need to go to :
# https://console.cloud.google.com/apis/credentials/oauthclient/322165384303-1k9tckicc9918m1kgqeit1bdg9vln021.apps.googleusercontent.com?project=rails-project-302302&supportedpurview=project
# and add another authorized uri
  resources :reactions
  resources :dreams do
    resources :reactions, only: [:new, :index]
  end
  resources :themes
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin.html.erb
    <%= link_to "Log Out", logout_path, method: :delete %>
    <%= link_to "Add New Dream", new_dream_path %>
    <%= link_to "View All Dreams", dreams_path %>
    <%= link_to "View All Themes", themes_path %>
    <%= link_to "Home", user_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header><%= nav_bar %></header>

  <div id="content"><%= yield %></div>

  <footer>Copyright <%= Time.now.year %></footer>
  </body>
</html>